Map_Config: Map_IO_Downloaded_Configuration.cpp OSM_Parser.cpp
	g++ -Wall -Werror -std=c++17 -I/usr/local/include Map_IO_Downloaded_Configuration.cpp OSM_Parser.cpp -o Map_Config -L/usr/local/lib -ltinyxml2

clean:
	rm -f Map_Config
